---
- name: Create AI stack directories and docker-compose file
  hosts: all
  become: true

  vars:
    ai_base_path: /opt/ai-stack
    ai_directories:
      - ollama
      - openwebui
      - comfyui/models
      - comfyui/hf-hub
      - comfyui/torch-hub
      - comfyui/input
      - comfyui/output
      - comfyui/workflows
      - sillytavern
      - sillytavern/sillytavern-extensions
      - sillytavern/sillytavern-plugins

    ai_compose_file: "{{ ai_base_path }}/docker-compose.yml"

  tasks:
    - name: Create base directory
      ansible.builtin.file:
        path: "{{ ai_base_path }}"
        state: directory
        mode: "0755"

    - name: Create AI service directories
      ansible.builtin.file:
        path: "{{ ai_base_path }}/{{ item }}"
        state: directory
        mode: "0755"
      loop: "{{ ai_directories }}"

    - name: Write docker-compose.yml for AI stack
      ansible.builtin.copy:
        dest: "{{ ai_compose_file }}"
        mode: "0644"
        content: |
          services:
            ollama:
              image: ollama/ollama:latest
              container_name: ollama
              restart: unless-stopped
              ports:
                - "11434:11434"
              volumes:
                - /opt/ai-stack/ollama:/root/.ollama
              gpus: all

            openwebui:
              image: ghcr.io/open-webui/open-webui:latest
              container_name: openwebui
              restart: unless-stopped
              depends_on:
                - ollama
              ports:
                - "3000:8080"
              environment:
                - OLLAMA_BASE_URL=http://ollama:11434
              volumes:
                - /opt/ai-stack/openwebui:/app/backend/data

            sillytavern:
              container_name: sillytavern
              image: ghcr.io/sillytavern/sillytavern:latest
              ports:
                - "8000:8000"
              volumes:
                - /opt/ai-stack/sillytavern/config:/home/node/app/config
                - /opt/ai-stack/sillytavern/data:/home/node/app/data
                - /opt/ai-stack/sillytavern/sillytavern-extensions:/home/node/app/public/scripts/extensions/third-party
                - /opt/ai-stack/sillytavern/sillytavern-plugins:/home/node/app/plugins

            comfyui:
              image: yanwk/comfyui-boot:cu130-slim
              container_name: comfyui
              ports:
                - "8188:8188"
              volumes:
                - /opt/ai-stack/comfyui/models:/root/ComfyUI/models
                - /opt/ai-stack/comfyui/hf-hub:/root/.cache/huggingface/hub
                - /opt/ai-stack/comfyui/torch-hub:/root/.cache/torch/hub
                - /opt/ai-stack/comfyui/input:/root/ComfyUI/input
                - /opt/ai-stack/comfyui/output:/root/ComfyUI/output
                - /opt/ai-stack/comfyui/workflows:/root/ComfyUI/user/default/workflows
              environment:
                - NVIDIA_VISIBLE_DEVICES=all
                - NVIDIA_DRIVER_CAPABILITIES=compute,utility
                - CLI_ARGS="--disable-xformers"
              gpus: all




    - name: Bring up AI stack with docker compose
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ ai_base_path }}"
      register: compose_up
      changed_when: "'Started' in compose_up.stdout or 'Recreated' in compose_up.stdout or 'Created' in compose_up.stdout"
      failed_when: compose_up.rc != 0
