---
- name: Install Docker Engine from official Docker repo (Ubuntu) - AWX friendly
  hosts: all
  become: true
  gather_facts: true

  vars:
    # SET THIS IN AWX as an extra var, or define per-inventory/group/host vars
    docker_user: "mread"

    docker_keyring_dir: /etc/apt/keyrings
    docker_keyring_path: /etc/apt/keyrings/docker.gpg

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: "{{ docker_keyring_dir }}"
        state: directory
        mode: "0755"

    - name: Download Docker ASCII armored GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.asc
        mode: "0644"

    - name: Dearmor Docker GPG key into apt keyring
      ansible.builtin.command:
        cmd: "gpg --dearmor -o {{ docker_keyring_path }} /tmp/docker.asc"
      args:
        creates: "{{ docker_keyring_path }}"

    - name: Ensure Docker keyring is readable by apt
      ansible.builtin.file:
        path: "{{ docker_keyring_path }}"
        mode: "0644"

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ ansible_architecture | lower | regex_replace('x86_64','amd64')
          | regex_replace('aarch64','arm64') }} signed-by={{ docker_keyring_path }}]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        filename: docker
        state: present
        update_cache: true

    - name: Install Docker Engine + CLI + containerd + plugins
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

    - name: Add chosen user to docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true

    - name: Cleanup temp key
      ansible.builtin.file:
        path: /tmp/docker.asc
        state: absent
